"""CropGuard Seed Data.

Provides realistic seed data for 5 crops, 15 diseases, and 30 treatments.
Disease class_labels follow the PlantVillage naming convention.
"""

CROPS = [
    {
        "name": "Tomato",
        "scientific_name": "Solanum lycopersicum",
        "description": "A widely cultivated fruit vegetable, essential to global diets and highly susceptible to fungal and bacterial diseases.",
    },
    {
        "name": "Wheat",
        "scientific_name": "Triticum aestivum",
        "description": "A staple cereal crop grown worldwide, vulnerable to rust diseases and powdery mildew in humid conditions.",
    },
    {
        "name": "Rice",
        "scientific_name": "Oryza sativa",
        "description": "The primary food crop for more than half the world's population, particularly susceptible to blast and bacterial blight.",
    },
    {
        "name": "Maize",
        "scientific_name": "Zea mays",
        "description": "A high-yield cereal crop used for food, feed, and industry, commonly affected by leaf blight and rust.",
    },
    {
        "name": "Potato",
        "scientific_name": "Solanum tuberosum",
        "description": "A globally important root vegetable, historically devastated by late blight and still susceptible to multiple fungal diseases.",
    },
]

DISEASES = [
    # Tomato (3)
    {
        "crop_name": "Tomato",
        "name": "Early Blight",
        "description": "Early blight is a fungal disease caused by Alternaria solani that attacks tomato plants at all stages. It causes significant defoliation, fruit loss, and reduced yields. The disease spreads rapidly in warm, humid conditions and can devastate crops if left untreated.",
        "severity": "medium",
        "symptoms": [
            "Dark brown circular spots with concentric rings on lower leaves",
            "Yellow halo surrounding the lesions",
            "Premature leaf drop starting from the bottom of the plant",
            "Stem lesions near the soil line in severe cases",
            "Small, sunken dark spots on fruit",
        ],
        "causes": "Caused by the fungus Alternaria solani. Spreads through infected plant debris, soil, and water splash. Favoured by temperatures of 24–29°C and high humidity.",
        "prevention": "Use certified disease-free seeds, practice crop rotation, remove infected debris, and avoid overhead irrigation. Maintain proper plant spacing for airflow.",
        "class_label": "Tomato___Early_blight",
    },
    {
        "crop_name": "Tomato",
        "name": "Late Blight",
        "description": "Late blight, caused by Phytophthora infestans, is one of the most destructive tomato diseases. It was responsible for the Irish Potato Famine and remains a major threat today. It can destroy entire fields within days under favourable conditions.",
        "severity": "critical",
        "symptoms": [
            "Water-soaked, greyish-green lesions on leaves that quickly turn brown",
            "White fuzzy mould on the underside of leaves in humid conditions",
            "Dark streaks on stems and petioles",
            "Brown, greasy-looking patches on fruit",
            "Rapid collapse of plant tissues",
        ],
        "causes": "Caused by the oomycete Phytophthora infestans. Spreads through airborne sporangia. Favoured by cool temperatures (10–20°C) and prolonged leaf wetness.",
        "prevention": "Plant resistant varieties, avoid overhead irrigation, remove volunteer plants, and apply preventive fungicides before disease onset.",
        "class_label": "Tomato___Late_blight",
    },
    {
        "crop_name": "Tomato",
        "name": "Leaf Mold",
        "description": "Leaf mold is a fungal disease caused by Passalora fulva (formerly Cladosporium fulvum). It primarily affects greenhouse-grown tomatoes and can cause significant yield losses through defoliation in high-humidity environments.",
        "severity": "medium",
        "symptoms": [
            "Pale green or yellowish spots on the upper leaf surface",
            "Olive-brown to greyish-purple velvety mould patches on the underside",
            "Affected leaves curl upward and wither",
            "Severe cases cause total defoliation",
        ],
        "causes": "Caused by the fungus Passalora fulva. Spread through airborne conidia. Thrives at 90%+ relative humidity and temperatures of 22–25°C.",
        "prevention": "Improve greenhouse ventilation, avoid excessive humidity, plant resistant varieties, and promptly remove infected leaves.",
        "class_label": "Tomato___Leaf_Mold",
    },
    # Wheat (3)
    {
        "crop_name": "Wheat",
        "name": "Yellow Rust",
        "description": "Yellow rust (stripe rust), caused by Puccinia striiformis, is one of the most damaging wheat diseases globally. It spreads rapidly in cool, moist conditions and can cause yield losses of 10–70% in susceptible varieties.",
        "severity": "high",
        "symptoms": [
            "Bright yellow-orange pustules arranged in stripes along the leaves",
            "Yellow powdery spore masses that rub off on fingers",
            "Leaf tissue turns pale green then yellow around pustules",
            "Severe infection causes premature leaf senescence",
            "Stunted plant growth and shriveled grains",
        ],
        "causes": "Caused by Puccinia striiformis f.sp. tritici. Spreads through airborne urediniospores. Favoured by temperatures of 10–15°C and leaf wetness.",
        "prevention": "Grow resistant varieties, apply fungicides at flag leaf stage, practice early sowing to avoid peak infection periods.",
        "class_label": "Wheat___Yellow_rust",
    },
    {
        "crop_name": "Wheat",
        "name": "Powdery Mildew",
        "description": "Powdery mildew, caused by Blumeria graminis, is a widespread fungal disease of wheat. Unlike most fungi, it thrives in dry conditions with high humidity and can significantly reduce photosynthetic capacity and grain filling.",
        "severity": "medium",
        "symptoms": [
            "White, powdery fungal growth on upper leaf surfaces",
            "Cottony patches that may turn grey or tan with age",
            "Yellowing of infected tissue beneath the white coating",
            "Reduced tillering and head development in severe cases",
        ],
        "causes": "Caused by Blumeria graminis f.sp. tritici. Spread by airborne conidia. Favoured by dense canopies, high nitrogen, and moderate temperatures (15–22°C).",
        "prevention": "Use resistant varieties, reduce nitrogen fertilisation, maintain adequate plant spacing, and apply fungicides at first symptom appearance.",
        "class_label": "Wheat___Powdery_mildew",
    },
    {
        "crop_name": "Wheat",
        "name": "Septoria Leaf Blotch",
        "description": "Septoria tritici blotch, caused by Zymoseptoria tritici, is the most economically important fungal disease of wheat in many temperate regions. It causes significant yield losses through destruction of the flag leaf and upper canopy.",
        "severity": "high",
        "symptoms": [
            "Pale green or greyish-brown lesions bounded by leaf veins",
            "Small black dots (pycnidia) visible within the lesions",
            "Lesions expand and merge causing large necrotic areas",
            "Severe damage to flag leaf reduces grain filling",
        ],
        "causes": "Caused by Zymoseptoria tritici. Spreads through rain-splashed pycnidiospores. Favoured by cool, wet weather during stem elongation.",
        "prevention": "Grow resistant varieties, practice crop rotation, use clean seed, delay sowing in high-risk areas, and apply fungicides at flag leaf emergence.",
        "class_label": "Wheat___Septoria_leaf_blotch",
    },
    # Rice (3)
    {
        "crop_name": "Rice",
        "name": "Blast",
        "description": "Rice blast, caused by Magnaporthe oryzae, is the most devastating rice disease worldwide. It attacks leaves, nodes, necks, and panicles, causing total crop failure in severe epidemics. It affects rice at all growth stages.",
        "severity": "critical",
        "symptoms": [
            "Spindle-shaped lesions with grey centres and brown borders on leaves",
            "Diamond or eye-shaped spots with yellow borders on leaves",
            "Collar rot at the junction of leaf and leaf sheath",
            "Node blast causing stem breakage",
            "Panicle neck rot causing white or unfilled grains",
        ],
        "causes": "Caused by Magnaporthe oryzae. Spreads through airborne conidia. Favoured by high humidity, temperatures of 24–28°C, and high nitrogen application.",
        "prevention": "Plant resistant varieties, use balanced fertilisation, avoid excess nitrogen, maintain good water management, and apply preventive fungicides.",
        "class_label": "Rice___Blast",
    },
    {
        "crop_name": "Rice",
        "name": "Bacterial Blight",
        "description": "Bacterial blight, caused by Xanthomonas oryzae pv. oryzae, is one of the most serious bacterial diseases of rice. It can cause yield losses of 20–30% in susceptible varieties and up to 75% in severe epidemics.",
        "severity": "high",
        "symptoms": [
            "Water-soaked yellowing at the leaf tips and margins",
            "Yellowing progresses toward the leaf base as a wavy lesion",
            "Leaves turn yellow then straw-coloured and die",
            "Milky or opaque bacterial ooze dries to yellow crusts",
            "In kresek phase, young seedlings wilt and die",
        ],
        "causes": "Caused by Xanthomonas oryzae pv. oryzae. Spreads through infected water, wind-driven rain, and contaminated implements. Favoured by flood conditions.",
        "prevention": "Plant resistant varieties, avoid excessive nitrogen, drain fields after heavy rain, use disease-free seed, and avoid working in wet fields.",
        "class_label": "Rice___Bacterial_blight",
    },
    {
        "crop_name": "Rice",
        "name": "Brown Spot",
        "description": "Brown spot disease, caused by Cochliobolus miyabeanus, is a widespread seedborne disease associated with nutrient-deficient soils. It contributed to the Great Bengal Famine of 1943 and remains an important yield-reducing disease.",
        "severity": "medium",
        "symptoms": [
            "Circular to oval brown spots with a light brown or grey centre",
            "Dark brown borders surrounding the lesions",
            "Spots may have a yellow halo in susceptible varieties",
            "Severe infection causes leaf blight and reduced photosynthesis",
            "Infected grains show dark brown discolouration",
        ],
        "causes": "Caused by Cochliobolus miyabeanus. Spread through infected seed and airborne conidia. Associated with potassium and silicon deficiency in soil.",
        "prevention": "Improve soil nutrition especially potassium and silicon, use disease-free seed, treat seed with fungicides, and practice crop rotation.",
        "class_label": "Rice___Brown_spot",
    },
    # Maize (3)
    {
        "crop_name": "Maize",
        "name": "Northern Leaf Blight",
        "description": "Northern leaf blight, caused by Exserohilum turcicum, is a major foliar disease of maize worldwide. It reduces photosynthetic area, resulting in yield losses of 30–50% in severe cases. The disease is particularly damaging when infection occurs before silking.",
        "severity": "high",
        "symptoms": [
            "Long elliptical cigar-shaped grey-green to tan lesions",
            "Lesions typically 2.5–15 cm long and run parallel to leaf veins",
            "Lesions turn tan and necrotic with dark green to black edges",
            "Olive-green to black sporulation visible within lesions in moist conditions",
            "Premature death of leaves in severe infections",
        ],
        "causes": "Caused by Exserohilum turcicum. Spreads through airborne conidia from infected crop residue. Favoured by temperatures of 18–27°C and prolonged leaf wetness.",
        "prevention": "Plant resistant hybrids, practice crop rotation, incorporate crop residue, and apply fungicides at early tassel stage if risk is high.",
        "class_label": "Maize___Northern_Leaf_Blight",
    },
    {
        "crop_name": "Maize",
        "name": "Common Rust",
        "description": "Common rust, caused by Puccinia sorghi, is widely distributed in all maize-growing regions. While rarely causing total crop failure, it consistently reduces yields through photosynthetic losses. Severe infections can cause significant economic losses in susceptible varieties.",
        "severity": "medium",
        "symptoms": [
            "Golden to cinnamon-brown oval to elongated pustules on both leaf surfaces",
            "Powdery reddish-brown spores that rub off on hands",
            "Pustules turn dark brown to black as they mature",
            "Severe infection causes leaf yellowing and premature death",
            "Heavy rust on husks reduces ear fill",
        ],
        "causes": "Caused by Puccinia sorghi. Spreads via airborne urediniospores. Favoured by cool temperatures (16–23°C), dew, and high humidity.",
        "prevention": "Plant rust-resistant hybrids, apply fungicides when 5% of leaf area is affected, and avoid late planting which coincides with high spore loads.",
        "class_label": "Maize___Common_rust",
    },
    {
        "crop_name": "Maize",
        "name": "Gray Leaf Spot",
        "description": "Gray leaf spot, caused by Cercospora zeae-maydis, is one of the most yield-limiting diseases of maize. It thrives in conservation tillage systems and can cause severe epidemics in warm, humid areas with poor air drainage.",
        "severity": "high",
        "symptoms": [
            "Rectangular pale-brown to grey lesions bounded by leaf veins",
            "Lesions initially appear as small tan spots with yellow halos",
            "Lesions expand to form long narrow rectangular shapes",
            "Greyish-brown discolouration with distinct parallel margins",
            "Severe blighting causes premature death of most leaf area",
        ],
        "causes": "Caused by Cercospora zeae-maydis. Primary inoculum from infected crop debris in minimum-tillage fields. Favoured by warm temperatures and prolonged dew periods.",
        "prevention": "Rotate with non-host crops, till infected residue, plant resistant hybrids, and apply fungicides at tasselling if disease is present.",
        "class_label": "Maize___Gray_leaf_spot",
    },
    # Potato (3)
    {
        "crop_name": "Potato",
        "name": "Late Blight",
        "description": "Potato late blight, caused by Phytophthora infestans, is the most destructive disease of potatoes globally and historically caused the Irish Potato Famine. It can destroy entire fields within days and makes tubers unmarketable.",
        "severity": "critical",
        "symptoms": [
            "Irregular water-soaked lesions on leaves, usually starting at leaf tips or edges",
            "Lesions turn brown to black with a greasy appearance",
            "White sporulation on the underside of lesions in humid conditions",
            "Stems develop dark brown lesions and collapse",
            "Tubers show reddish-brown internal rot with granular texture",
        ],
        "causes": "Caused by Phytophthora infestans. Spreads through air, water, and infected tubers. Favoured by cool (10–20°C), moist conditions.",
        "prevention": "Use certified disease-free seed tubers, plant resistant varieties, apply preventive fungicides before symptoms appear, and destroy volunteer plants.",
        "class_label": "Potato___Late_blight",
    },
    {
        "crop_name": "Potato",
        "name": "Early Blight",
        "description": "Potato early blight is caused by Alternaria solani and is a common, yield-reducing disease found wherever potatoes are grown. Although rarely as devastating as late blight, it can cause significant defoliation and tuber blemishing, particularly in stressed plants.",
        "severity": "medium",
        "symptoms": [
            "Dark brown to black spots with concentric rings resembling a target",
            "Yellow halo surrounding the spots on older lower leaves",
            "Lesions expand and merge causing extensive leaf death",
            "Stem lesions with concentric rings and dark colour",
            "Tuber lesions are dark, sunken, and circular with raised margins",
        ],
        "causes": "Caused by Alternaria solani. Spreads by airborne conidia from infected debris. Favoured by warm temperatures (24–29°C), heavy dew, and plant stress.",
        "prevention": "Use certified seed, practice crop rotation, maintain adequate nutrition, avoid excessive nitrogen, and apply fungicides preventively.",
        "class_label": "Potato___Early_blight",
    },
    {
        "crop_name": "Potato",
        "name": "Black Leg",
        "description": "Black leg is a bacterial disease of potato caused by Pectobacterium atrosepticum. It causes stem base rotting and can lead to total plant collapse. The disease also causes soft rot of tubers in storage, leading to significant post-harvest losses.",
        "severity": "high",
        "symptoms": [
            "Black slimy rot at the base of the stem extending upward",
            "Yellowing and upward rolling of leaves above the rotted stem",
            "Wilting of the entire plant despite moist soil",
            "Hollow, water-soaked cavities at the stem base with foul smell",
            "Tubers show brown to black wet rot beginning at the stolon end",
        ],
        "causes": "Caused by Pectobacterium atrosepticum and related species. Spread through infected seed tubers and wet soil. Favoured by waterlogged conditions and cool temperatures.",
        "prevention": "Use certified disease-free seed tubers, ensure good soil drainage, avoid cutting seed tubers in wet conditions, and do not store damaged tubers.",
        "class_label": "Potato___Black_leg",
    },
]

TREATMENTS = [
    # Tomato Early Blight
    {
        "disease_class_label": "Tomato___Early_blight",
        "name": "Chlorothalonil Foliar Spray",
        "type": "chemical",
        "description": "Chlorothalonil is a broad-spectrum contact fungicide effective against early blight. Regular applications protect leaf tissue and prevent spore germination, significantly reducing disease spread.",
        "active_ingredient": "Chlorothalonil 75% WP",
        "dosage": "2 g per litre of water",
        "application_method": "Spray both upper and lower leaf surfaces thoroughly until runoff. Begin applications at first symptom or preventively in high-risk conditions.",
        "timing": "Every 7–10 days from first symptom appearance or at disease onset",
        "waiting_period": "7 days before harvest",
        "cost_estimate": "low",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Tomato___Early_blight",
        "name": "Neem Oil Spray",
        "type": "organic",
        "description": "Neem oil acts as a natural fungicide and insecticide, disrupting fungal growth and repelling aphids that can spread disease. It is safe for beneficial insects when applied in the evening.",
        "active_ingredient": "Azadirachtin (neem oil extract)",
        "dosage": "5 ml neem oil per litre of water with a few drops of dish soap as emulsifier",
        "application_method": "Spray entire plant thoroughly in the early morning or evening to avoid leaf burn. Ensure coverage of undersides of leaves.",
        "timing": "Every 7 days, or after rainfall",
        "waiting_period": "1 day before harvest",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Tomato Late Blight
    {
        "disease_class_label": "Tomato___Late_blight",
        "name": "Metalaxyl + Mancozeb",
        "type": "chemical",
        "description": "This combination systemic and contact fungicide is highly effective against Phytophthora. Metalaxyl penetrates the plant tissue while mancozeb provides surface protection.",
        "active_ingredient": "Metalaxyl 8% + Mancozeb 64% WP",
        "dosage": "2.5 g per litre of water",
        "application_method": "Thorough coverage of all plant parts. Apply preventively before disease onset or at first signs of infection. Rotate with other fungicides to avoid resistance.",
        "timing": "Every 7 days during wet, cool weather; every 10–14 days otherwise",
        "waiting_period": "10 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Tomato___Late_blight",
        "name": "Copper Oxychloride",
        "type": "organic",
        "description": "Copper oxychloride is an approved organic fungicide that provides protective action against late blight. It must be applied before infection as it has no curative activity.",
        "active_ingredient": "Copper oxychloride 50% WP",
        "dosage": "3 g per litre of water",
        "application_method": "Apply to all foliage ensuring complete coverage. Reapply after heavy rain. Avoid overapplication as copper can accumulate in soil.",
        "timing": "Every 7–10 days during high-risk periods; preventive use strongly recommended",
        "waiting_period": "3 days before harvest",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Tomato Leaf Mold
    {
        "disease_class_label": "Tomato___Leaf_Mold",
        "name": "Difenoconazole Spray",
        "type": "chemical",
        "description": "Difenoconazole is a systemic triazole fungicide with both protectant and curative activity against leaf mold. It inhibits sterol biosynthesis in the fungus.",
        "active_ingredient": "Difenoconazole 25% EC",
        "dosage": "0.5 ml per litre of water",
        "application_method": "Spray thoroughly with emphasis on underside of leaves where the pathogen sporulates. Apply at first sign of disease.",
        "timing": "Every 10–14 days; 2–3 applications per season",
        "waiting_period": "14 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Tomato___Leaf_Mold",
        "name": "Improved Greenhouse Ventilation",
        "type": "cultural",
        "description": "Improving airflow within greenhouse structures dramatically reduces humidity levels that favour leaf mold. Installing side vents, fans, or ridge vents keeps humidity below the 90% threshold the pathogen requires.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Install or open greenhouse vents, side openings, and fans. Avoid wetting foliage during irrigation. Space plants to improve air circulation.",
        "timing": "Continuous management throughout growing season",
        "waiting_period": "None",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": True,
    },
    # Wheat Yellow Rust
    {
        "disease_class_label": "Wheat___Yellow_rust",
        "name": "Propiconazole Fungicide",
        "type": "chemical",
        "description": "Propiconazole is a highly effective systemic triazole fungicide for stripe rust control. Applied at first pustule appearance, it can halt disease progression and protect the flag leaf.",
        "active_ingredient": "Propiconazole 25% EC",
        "dosage": "1 ml per litre of water",
        "application_method": "Apply as foliar spray ensuring thorough canopy coverage. A single well-timed application at flag leaf emergence is often sufficient.",
        "timing": "At flag leaf emergence (GS 37–41) or at first pustule appearance",
        "waiting_period": "35 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Wheat___Yellow_rust",
        "name": "Resistant Variety Selection",
        "type": "cultural",
        "description": "Growing rust-resistant wheat varieties is the most economical and environmentally friendly control method. Modern resistant varieties can reduce stripe rust severity by over 90% without chemical inputs.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Select certified seed of varieties with high resistance ratings for your region. Contact local agricultural extension for current resistance ratings as races evolve.",
        "timing": "At planting — variety selection is a pre-season decision",
        "waiting_period": "None",
        "cost_estimate": "low",
        "effectiveness": "high",
        "is_certified_organic": True,
    },
    # Wheat Powdery Mildew
    {
        "disease_class_label": "Wheat___Powdery_mildew",
        "name": "Tebuconazole Spray",
        "type": "chemical",
        "description": "Tebuconazole is a broad-spectrum triazole fungicide with both protectant and curative properties against powdery mildew. It also provides some control of septoria and rusts.",
        "active_ingredient": "Tebuconazole 25.9% EC",
        "dosage": "1 ml per litre of water",
        "application_method": "Apply as foliar spray at the first sign of powdery mildew, typically at the stem extension or heading growth stages. Ensure thorough canopy coverage.",
        "timing": "At GS 30–39 (stem extension) when disease threshold is reached",
        "waiting_period": "42 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Wheat___Powdery_mildew",
        "name": "Sulphur Dust Application",
        "type": "organic",
        "description": "Sulphur is an approved organic fungicide effective against powdery mildew. It works by direct contact and fumigant action against the fungal spores and mycelium.",
        "active_ingredient": "Wettable sulphur 80% WP",
        "dosage": "3 g per litre of water",
        "application_method": "Apply as foliar spray during cooler hours. Do not apply when temperatures exceed 32°C to avoid phytotoxicity. Reapply after rain.",
        "timing": "Every 7–10 days at first sign of powdery mildew",
        "waiting_period": "1 day before harvest",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Wheat Septoria
    {
        "disease_class_label": "Wheat___Septoria_leaf_blotch",
        "name": "Azoxystrobin + Propiconazole",
        "type": "chemical",
        "description": "This premix combines a strobilurin (azoxystrobin) with a triazole (propiconazole) for broad-spectrum disease control including septoria, rusts, and powdery mildew. The combination reduces the risk of fungicide resistance.",
        "active_ingredient": "Azoxystrobin 18.2% + Propiconazole 11.4% SC",
        "dosage": "0.8 ml per litre of water",
        "application_method": "Apply at flag leaf emergence timing (GS 37–39) for maximum protection of the upper canopy. Use a spray volume of at least 200 L/ha for good coverage.",
        "timing": "Flag leaf timing (GS 37–39) — single application is usually sufficient",
        "waiting_period": "35 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Wheat___Septoria_leaf_blotch",
        "name": "Crop Rotation with Non-Cereals",
        "type": "cultural",
        "description": "Rotating wheat with non-cereal crops such as oilseed rape, legumes, or vegetables breaks the disease cycle by allowing infected crop debris to decompose before the next wheat crop is sown.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Avoid growing wheat after wheat. At minimum, include one non-cereal break crop every 3 years. This also helps reduce other cereal-specific pests and diseases.",
        "timing": "Implement as a multi-year rotation plan",
        "waiting_period": "None",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Rice Blast
    {
        "disease_class_label": "Rice___Blast",
        "name": "Tricyclazole Spray",
        "type": "chemical",
        "description": "Tricyclazole is a specific systemic fungicide for rice blast. It inhibits melanin biosynthesis in the pathogen, preventing penetration of host tissue. It is the most widely used fungicide for blast management in Asia.",
        "active_ingredient": "Tricyclazole 75% WP",
        "dosage": "0.6 g per litre of water",
        "application_method": "Apply as foliar spray ensuring thorough coverage of all leaves. Critical timing is at panicle initiation and again at boot stage for neck blast prevention.",
        "timing": "At panicle initiation (PI) and again 10–15 days later for neck protection",
        "waiting_period": "14 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Rice___Blast",
        "name": "Silicon Soil Amendment",
        "type": "organic",
        "description": "Silicon application strengthens cell walls in rice plants, reducing fungal penetration and disease severity. Silicon-deficient soils in tropical regions are associated with higher blast incidence.",
        "active_ingredient": "Calcium silicate or silica slag",
        "dosage": "1–2 tonnes per hectare incorporated into soil",
        "application_method": "Incorporate silicon fertiliser into soil before transplanting or apply as topdressing. Rice straw recycling also helps maintain soil silicon levels.",
        "timing": "At land preparation before transplanting",
        "waiting_period": "None",
        "cost_estimate": "medium",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Rice Bacterial Blight
    {
        "disease_class_label": "Rice___Bacterial_blight",
        "name": "Copper Hydroxide Spray",
        "type": "chemical",
        "description": "Copper-based bactericides provide protective action against bacterial blight. While not curative once infection is established, timely applications can reduce spread to healthy tissue.",
        "active_ingredient": "Copper hydroxide 77% WP",
        "dosage": "2 g per litre of water",
        "application_method": "Apply as foliar spray beginning when plants show first symptoms or after storm damage. Ensure complete coverage. Do not apply during flowering.",
        "timing": "At first symptom appearance and after typhoon or flood events",
        "waiting_period": "7 days before harvest",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Rice___Bacterial_blight",
        "name": "Water Management & Drainage",
        "type": "cultural",
        "description": "Proper water management is critical for bacterial blight control. Draining flooded fields after heavy rainfall or typhoons reduces the waterborne spread of Xanthomonas. Avoid flooding injured or diseased fields.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Drain fields within 24 hours of severe weather events. Avoid deep flooding in fields with disease history. Use intermittent irrigation where possible.",
        "timing": "Throughout growing season, especially after storm events",
        "waiting_period": "None",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Rice Brown Spot
    {
        "disease_class_label": "Rice___Brown_spot",
        "name": "Iprodione Seed Treatment",
        "type": "chemical",
        "description": "Iprodione seed treatment provides protection against seedborne Cochliobolus miyabeanus. Treating seed before sowing dramatically reduces primary inoculum and seedling infection in the nursery.",
        "active_ingredient": "Iprodione 50% WP",
        "dosage": "2 g per kg of seed for seed treatment",
        "application_method": "Mix fungicide with a small amount of water to make a slurry. Coat seed evenly and allow to dry before sowing. Alternatively apply as nursery spray.",
        "timing": "Before sowing — seed treatment is a pre-planting intervention",
        "waiting_period": "None (seed treatment)",
        "cost_estimate": "low",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Rice___Brown_spot",
        "name": "Balanced Potassium Fertilisation",
        "type": "cultural",
        "description": "Brown spot is strongly associated with potassium and silicon deficiency. Correcting nutrient imbalances through balanced fertilisation significantly reduces disease severity and improves plant tolerance.",
        "active_ingredient": None,
        "dosage": "60 kg K2O per hectare (adjust based on soil test)",
        "application_method": "Apply potassium fertiliser (muriate of potash or sulphate of potash) based on soil test results. Split application — half at basal and half at tillering.",
        "timing": "At land preparation (basal) and at active tillering stage",
        "waiting_period": "None",
        "cost_estimate": "low",
        "effectiveness": "high",
        "is_certified_organic": True,
    },
    # Maize Northern Leaf Blight
    {
        "disease_class_label": "Maize___Northern_Leaf_Blight",
        "name": "Propiconazole Maize Spray",
        "type": "chemical",
        "description": "Propiconazole provides excellent protectant and curative activity against northern leaf blight when applied at the right timing. Applications just before tasselling protect the upper canopy during grain fill.",
        "active_ingredient": "Propiconazole 25% EC",
        "dosage": "1 ml per litre of water",
        "application_method": "Apply as foliar spray targeting the upper leaf canopy. Use ground spray equipment or aerial application for large fields. Apply at first lesion appearance.",
        "timing": "At first tassel emergence (VT stage) or when lesions appear on third leaf below the ear",
        "waiting_period": "30 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Maize___Northern_Leaf_Blight",
        "name": "Infected Residue Incorporation",
        "type": "cultural",
        "description": "Northern leaf blight survives on infected maize residue. Deep incorporation or burning of residue after harvest dramatically reduces the primary inoculum for the following season.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Plough infected stubble and residue to a depth of 15–20 cm after harvest. In conservation tillage systems, applying nitrogenous fertiliser to accelerate residue decomposition may help.",
        "timing": "Immediately after harvest before next planting season",
        "waiting_period": "None",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Maize Common Rust
    {
        "disease_class_label": "Maize___Common_rust",
        "name": "Mancozeb Preventive Spray",
        "type": "chemical",
        "description": "Mancozeb is a broad-spectrum contact fungicide effective as a protective treatment against rust diseases. Applied before infection establishes, it prevents urediniospore germination on leaf surfaces.",
        "active_ingredient": "Mancozeb 75% WP",
        "dosage": "2.5 g per litre of water",
        "application_method": "Apply as preventive foliar spray ensuring complete coverage of all leaf surfaces. Reapply after heavy rainfall. Most effective when started at first rust pustule appearance.",
        "timing": "At first pustule appearance, then every 10–14 days",
        "waiting_period": "5 days before harvest",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Maize___Common_rust",
        "name": "Early Planting Strategy",
        "type": "cultural",
        "description": "Common rust urediniospores arrive on air currents later in the season. Early-sown maize completes its critical grain-filling stage before peak rust pressure, significantly reducing yield impact.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Plant at the earliest appropriate date for your region based on temperature and frost risk. Select early-maturing hybrids with good rust resistance ratings.",
        "timing": "Pre-season planning — implement at planting time",
        "waiting_period": "None",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Maize Gray Leaf Spot
    {
        "disease_class_label": "Maize___Gray_leaf_spot",
        "name": "Azoxystrobin Spray",
        "type": "chemical",
        "description": "Azoxystrobin is a strobilurin fungicide with broad-spectrum systemic activity against gray leaf spot. It works by interfering with mitochondrial respiration in the fungus.",
        "active_ingredient": "Azoxystrobin 23% SC",
        "dosage": "1 ml per litre of water",
        "application_method": "Apply at tasselling (VT) or early silking (R1) stage. Use spray equipment that ensures good coverage of the ear leaf and upper canopy.",
        "timing": "At VT/R1 stage when conditions favor disease, or when first lesions appear on leaves below the ear",
        "waiting_period": "28 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Maize___Gray_leaf_spot",
        "name": "No-Till to Minimum-Till Transition",
        "type": "cultural",
        "description": "Gray leaf spot is more severe in continuous no-till maize because infected residue is not buried. Switching to minimum-till or periodic moldboard ploughing reduces residue on the soil surface and the inoculum level.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Incorporate infected maize residue by disc or moldboard tillage after harvest. At minimum, alternate between no-till and full tillage every 2–3 years.",
        "timing": "After harvest before the next planting season",
        "waiting_period": "None",
        "cost_estimate": "medium",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Potato Late Blight
    {
        "disease_class_label": "Potato___Late_blight",
        "name": "Cymoxanil + Mancozeb",
        "type": "chemical",
        "description": "This combination of a systemic (cymoxanil) and contact (mancozeb) fungicide provides outstanding control of potato late blight. Cymoxanil has kickback activity against established infections while mancozeb protects new growth.",
        "active_ingredient": "Cymoxanil 8% + Mancozeb 64% WP",
        "dosage": "2.5 g per litre of water",
        "application_method": "Apply as foliar spray with a handheld or tractor-mounted boom sprayer. Ensure thorough coverage of all foliage. Begin applications preventively in high-risk conditions.",
        "timing": "Every 7 days during high-risk (cool, wet) weather; every 10–14 days otherwise",
        "waiting_period": "14 days before harvest",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Potato___Late_blight",
        "name": "Copper-Based Bordeaux Mixture",
        "type": "organic",
        "description": "Bordeaux mixture (copper sulphate + lime) has been used against potato late blight since the 19th century and remains one of the most effective organic fungicides available for this disease.",
        "active_ingredient": "Copper sulphate 1% + Lime 1%",
        "dosage": "10 g copper sulphate + 10 g slaked lime per litre of water",
        "application_method": "Prepare fresh mixture each time. Apply thoroughly to all plant surfaces. Do not apply in hot weather. Monitor for copper toxicity with repeated use.",
        "timing": "Every 7–10 days from emergence or when disease risk is high",
        "waiting_period": "3 days before harvest",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Potato Early Blight
    {
        "disease_class_label": "Potato___Early_blight",
        "name": "Chlorothalonil Potato Spray",
        "type": "chemical",
        "description": "Chlorothalonil provides reliable protective action against potato early blight. It is a multi-site fungicide with very low resistance risk, making it a valuable component of resistance management programs.",
        "active_ingredient": "Chlorothalonil 75% WP",
        "dosage": "2 g per litre of water",
        "application_method": "Apply as protectant before disease onset, or at first symptom. Ensure good coverage. Often used in combination with late blight fungicides.",
        "timing": "Every 7–10 days, preventively from 4 weeks before normal disease onset or after hail",
        "waiting_period": "7 days before harvest",
        "cost_estimate": "low",
        "effectiveness": "high",
        "is_certified_organic": False,
    },
    {
        "disease_class_label": "Potato___Early_blight",
        "name": "Crop Rotation & Debris Management",
        "type": "cultural",
        "description": "Early blight survives in infected potato residue and solanaceous weed hosts. A 3-year rotation away from potatoes, combined with thorough debris removal, significantly reduces inoculum build-up.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Rotate with non-solanaceous crops for at least 3 years. Remove all potato debris after harvest. Control solanaceous weeds (nightshade) in and around the field.",
        "timing": "Post-harvest debris management and pre-season rotation planning",
        "waiting_period": "None",
        "cost_estimate": "low",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
    # Potato Black Leg
    {
        "disease_class_label": "Potato___Black_leg",
        "name": "Certified Disease-Free Seed Tubers",
        "type": "cultural",
        "description": "The primary source of black leg infection is contaminated seed tubers. Using only certified, disease-free seed from tested stocks is the single most effective control measure for this bacterial disease.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Purchase only certified seed from reputable suppliers. Inspect seed before planting and discard any showing soft rot or discolouration. Do not save seed from infected crops.",
        "timing": "Pre-season seed selection — critical decision before planting",
        "waiting_period": "None",
        "cost_estimate": "medium",
        "effectiveness": "high",
        "is_certified_organic": True,
    },
    {
        "disease_class_label": "Potato___Black_leg",
        "name": "Soil Drainage Improvement",
        "type": "cultural",
        "description": "Black leg thrives in waterlogged, anaerobic soil conditions. Improving soil drainage and avoiding compaction reduces the conditions that favour bacterial multiplication and spread through the soil water.",
        "active_ingredient": None,
        "dosage": "N/A",
        "application_method": "Install tile drainage or raised beds in poorly draining fields. Avoid working wet soil to prevent compaction. Ridge potato rows high to promote drainage around the plant base.",
        "timing": "Infrastructure investment before planting; management throughout season",
        "waiting_period": "None",
        "cost_estimate": "high",
        "effectiveness": "medium",
        "is_certified_organic": True,
    },
]
